/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NauczycielIndexRouteImport } from './routes/nauczyciel/index'
import { Route as KoszykIndexRouteImport } from './routes/koszyk/index'
import { Route as KontoIndexRouteImport } from './routes/konto/index'
import { Route as SklepProductIdIndexRouteImport } from './routes/sklep.$productId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NauczycielIndexRoute = NauczycielIndexRouteImport.update({
  id: '/nauczyciel/',
  path: '/nauczyciel/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoszykIndexRoute = KoszykIndexRouteImport.update({
  id: '/koszyk/',
  path: '/koszyk/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoIndexRoute = KontoIndexRouteImport.update({
  id: '/konto/',
  path: '/konto/',
  getParentRoute: () => rootRouteImport,
} as any)
const SklepProductIdIndexRoute = SklepProductIdIndexRouteImport.update({
  id: '/sklep/$productId/',
  path: '/sklep/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/konto': typeof KontoIndexRoute
  '/koszyk': typeof KoszykIndexRoute
  '/nauczyciel': typeof NauczycielIndexRoute
  '/sklep/$productId': typeof SklepProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/konto': typeof KontoIndexRoute
  '/koszyk': typeof KoszykIndexRoute
  '/nauczyciel': typeof NauczycielIndexRoute
  '/sklep/$productId': typeof SklepProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/konto/': typeof KontoIndexRoute
  '/koszyk/': typeof KoszykIndexRoute
  '/nauczyciel/': typeof NauczycielIndexRoute
  '/sklep/$productId/': typeof SklepProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/konto' | '/koszyk' | '/nauczyciel' | '/sklep/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/konto' | '/koszyk' | '/nauczyciel' | '/sklep/$productId'
  id:
    | '__root__'
    | '/'
    | '/konto/'
    | '/koszyk/'
    | '/nauczyciel/'
    | '/sklep/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontoIndexRoute: typeof KontoIndexRoute
  KoszykIndexRoute: typeof KoszykIndexRoute
  NauczycielIndexRoute: typeof NauczycielIndexRoute
  SklepProductIdIndexRoute: typeof SklepProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nauczyciel/': {
      id: '/nauczyciel/'
      path: '/nauczyciel'
      fullPath: '/nauczyciel'
      preLoaderRoute: typeof NauczycielIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koszyk/': {
      id: '/koszyk/'
      path: '/koszyk'
      fullPath: '/koszyk'
      preLoaderRoute: typeof KoszykIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto/': {
      id: '/konto/'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sklep/$productId/': {
      id: '/sklep/$productId/'
      path: '/sklep/$productId'
      fullPath: '/sklep/$productId'
      preLoaderRoute: typeof SklepProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontoIndexRoute: KontoIndexRoute,
  KoszykIndexRoute: KoszykIndexRoute,
  NauczycielIndexRoute: NauczycielIndexRoute,
  SklepProductIdIndexRoute: SklepProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
